=== RainerW/XMLFit/model/src/main/resources/net/sourceforge/xmlfit/model/component.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://xmlfit.sourceforge.net/schema/1.0/component" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:comp="http://xmlfit.sourceforge.net/schema/1.0/component">

    <complexType name="Fixture" abstract="true">
        <attribute name="type" type="string" use="optional"></attribute>
    </complexType>

    <complexType name="ActionFixture">
    	<complexContent>
    		<extension base="comp:Fixture">
    			<sequence>
    				<element name="command" type="comp:Command"
    					maxOccurs="unbounded" minOccurs="0">
    				</element>
    			</sequence>

    			<attribute name="type" type="string" default="fit.ActionFixture"></attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="ColumnFixture">
    	<complexContent>
    		<extension base="comp:Fixture">
    			<sequence>
    				<element name="column" type="comp:Column"
    					maxOccurs="unbounded" minOccurs="1">
    				</element>
    				<element name="row" type="comp:Row" maxOccurs="unbounded" minOccurs="0"></element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="Command">
    	<sequence>
    		<element name="target" type="string" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="value" type="string" maxOccurs="unbounded"
    			minOccurs="0">
    		</element>
    		<element name="comment" type="string" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    	<attribute name="name" type="string" use="required"></attribute>
    </complexType>

    <complexType name="Column">
    	<attribute name="name" type="string" use="required"></attribute>
    </complexType>
    
    <complexType name="Row">
    	<sequence>
    		<element name="value" type="string" maxOccurs="unbounded"
    			minOccurs="1">
    		</element>
    	</sequence>
    	<attribute name="name" type="string" use="optional"></attribute>
    	<attribute name="comment" type="string" use="optional"></attribute>
    </complexType>


    <complexType name="Component">
    	<sequence minOccurs="0" maxOccurs="1">
    		<element name="parameter" type="comp:Parameter" minOccurs="0" maxOccurs="unbounded"></element>
    		<sequence maxOccurs="unbounded" minOccurs="0">
    			<group ref="comp:Fixture"></group>
    		</sequence>
    	</sequence>
    </complexType>

    <group name="Fixture">
      <choice>
      	<element name="tableFixture" type="comp:TabelFixture"></element>
      	<element name="actionFixture" type="comp:ActionFixture"></element>
      	<element name="columnFixture" type="comp:ColumnFixture"></element>
      	<element name="comment" type="comp:CommentFixture"></element>
      </choice>
    </group>

    <complexType name="Components">
    	<sequence>
    		<element name="component" type="comp:Component" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <complexType name="CommentFixture">
        <sequence>
        <element name="heading" type="string" maxOccurs="1" minOccurs="0">
        </element>
        <element name="description" type="string" maxOccurs="1" minOccurs="0"></element>
      </sequence></complexType>

    <element name="component" type="comp:Component"></element>

    <complexType name="TabelFixture">
    	<complexContent>
    		<extension base="comp:Fixture">
    			<sequence>
    				<element name="command" type="comp:Command"
    					maxOccurs="unbounded" minOccurs="0">
    				</element>
    				<element name="column" type="comp:Column" maxOccurs="unbounded" minOccurs="0"></element>
    				<element name="row" type="comp:Row"
    					maxOccurs="unbounded" minOccurs="0">
    				</element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>


    <complexType name="Parameter">
    	<sequence>
    		<element name="description" type="string" minOccurs="0" maxOccurs="1"></element>
    	</sequence>
    	<attribute name="name" type="string"></attribute>
    	<attribute name="required" type="boolean"></attribute>
    	<attribute name="defaultValue" type="string"></attribute>
    </complexType>
    
</schema>

=== RainerW/XMLFit/fit-transformer/src/test/resources/example-component.xml
<?xml version="1.0" encoding="UTF-8"?>
<component
	xmlns="http://xmlfit.sourceforge.net/schema/1.0/component" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://xmlfit.sourceforge.net/schema/1.0/component/component.xsd">
	
		<parameter name="testParam" defaultValue="Test Default Param Value" />
		<parameter name="password" defaultValue="Test Default Param Password" />
		<parameter name="username" defaultValue="Test Default Param Password" />
		<parameter name="parmInner" defaultValue="http://localhost:8080/" />
        <parameter name="parmOut" defaultValue="${parmInner}telcenter/" />
        
        <tableFixture type="db.Table">
        	<command name="name">
        		<target>detailTable</target>
        	</command>
        	<column name="id" />
        	<column name="detail"/>
        	<row>
        		<value>1</value>
        		<value>My Detail Text</value>
        	</row>
        </tableFixture>
        
        <tableFixture type="db.Table">
        	<command name="name">
        		<target>detailTable</target>
        	</command>
        	<column name="id" />
        	<column name="detail"/>
        	<column name="description"/>
        	<column name="email"/>
        	<row>
        		<value>1</value>
        		<value>My Detail Text</value>
        		<value>meine description</value>
        		<value>test@test.de</value>
        	</row>
        </tableFixture>
        
        <tableFixture type="db.Table">
        	<command name="name">
        		<target>detailTable</target>
        	</command>
        	<row>
        		<value>1</value>
        		<value>My Detail Text</value>
        		<value>meine description</value>
        		<value>test@test.de</value>
        	</row>
        </tableFixture>
        
        <actionFixture>
            <command name="testCommandName">
                <target>${parmOut}</target>
            </command>
        </actionFixture>
        
		<actionFixture>
			<command name="testCommandName">
				<target>${testParam}</target>
			</command>
		</actionFixture>
	
		<actionFixture>
			<command name="testCommandName">
				<target>testTarget</target>
			</command>
		</actionFixture>
		
		<actionFixture>
			<command name="testCommandName">
				<target>testTarget</target>
				<comment>Test Comment</comment>
			</command>
		</actionFixture>
		
		<actionFixture>
			<command name="testCommandName">
				<target>testTarget</target>
				<value>testValue</value>
			</command>
		</actionFixture>
		
		<actionFixture>
			<command name="testCommandName">
				<target>testTarget</target>
				<value>testValue</value>
				<comment>test Comment</comment>
			</command>
		</actionFixture>
		
		<actionFixture type="fit.SeleniumFixture">
			<command name="testCommandName">
				<target>testTarget</target>
				<value>testValue</value>
			</command>
		</actionFixture>
		
		<actionFixture type="fit.SeleniumFixture">
			<command name="testCommandName">
				<target>testTarget</target>
				<value>testValue</value>
				<comment>test Comment</comment>
			</command>
		</actionFixture>
		
		<actionFixture>
			<command name="testCommandName">
				<target>testTarget</target>
			</command>
			<command name="testCommandName">
				<target>testTarget</target>
				<comment>test Comment</comment>
			</command>
			<command name="testCommandName">
				<target>testTarget</target>
				<value>testValue</value>
			</command>
			<command name="testCommandName">
				<target>testTarget</target>
				<value>testValue</value>
				<comment>test Comment</comment>
			</command>
		</actionFixture>
	
		<actionFixture>
			<command name="testCommandName">
				<target>testTarget</target>
			</command>
			<command name="testCommandName">
				<target>testTarget</target>
				<comment>test Comment</comment>
			</command>
			<command name="testCommandName">
				<target>testTarget</target>
				<value>testValue</value>
			</command>
			<command name="testCommandName">
				<target>testTarget</target>
				<value>testValue</value>
			</command>
		</actionFixture>
		
		<actionFixture>
			<command name="testCommandName">
				<target>testTarget</target>
			</command>
			<command name="testCommandName">
				<target>testTarget</target>
				<comment>test Comment</comment>
			</command>
			<command name="testCommandName">
				<target>testTarget</target>
				<value>testValue</value>
			</command>
			<command name="testCommandName">
				<target>testTarget</target>
				<value>test value 1</value>
				<value>test value 2</value>
				<comment>test Comment</comment>
			</command>
		</actionFixture>
	
        <comment>
            <heading>${defaultData}User DB Setup</heading>
            <description>Setup the User DB for the Test.</description>
        </comment>
    
		<columnFixture type="UserDbFixture">
			<column name="id" />
			<column name="username" />
			<column name="password" />
			<row>
				<value>1</value>
				<value>${username}</value>
				<value>${password}</value>
			</row>
		</columnFixture>
		
        <comment>
            <heading>Login - for User ${username} and Password ${password}</heading>
            <description>The Fixture doese the Login with Username and Password.</description>
        </comment>
    
		<actionFixture>
			<command name="start">
				<target>LoginFixture</target>
				<comment>Starte Applikation mit einem Login</comment>
			</command>
			<command name="enter">
				<target>username</target>
				<value>${username}</value>
			</command>
			<command name="enter">
				<target>password</target>
				<value>${password}</value>
			</command>
			<command name="special">
				<target>test</target>
				<value>01</value>
				<value>02</value>
				<value>03</value>
			</command>
			<command name="type">
				<target>loginForm:username</target>
				<value>Christian.Baranowski@pro-pix.de</value>
			</command>
			<command name="getAll">
				<value>Test VALUE ONE</value>
				<value>VALUE TWO</value>
			</command>
		</actionFixture>

</component>
