=== RainerW/XMLFit/fit-extension/src/main/resources/xsd/AliasConfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.seitenbau.com/testing/AliasConfigurationFixture" xmlns:tns="http://www.seitenbau.com/testing/AliasConfigurationFixture"
  elementFormDefault="qualified">

  <element name="aliasConfiguration" type="tns:AliasConfiguration"></element>


  <complexType name="Alias">
        <sequence>
      <element name="value" type="string" maxOccurs="1" minOccurs="1"></element>
    </sequence>
    <attribute name="name" type="string" use="required"></attribute>
  </complexType>

  

  <complexType name="IndexAlias">
    <complexContent>
      <extension base="tns:Alias">
        <sequence>
          <element name="afterIndexValue" type="string" maxOccurs="1" minOccurs="1"></element>
        </sequence>


      </extension>
    </complexContent>
  </complexType>

  <complexType name="AliasConfiguration">
        <sequence maxOccurs="unbounded" minOccurs="0">
      <element name="alias" type="tns:Alias" maxOccurs="unbounded" minOccurs="0"></element>
      <element name="indexAlias" type="tns:IndexAlias" maxOccurs="unbounded" minOccurs="0"></element>
    </sequence>
  </complexType>
</schema>

=== RainerW/XMLFit/fit-extension/src/main/resources/xsd/element-alias-mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<aliasConfiguration xmlns="http://www.seitenbau.com/testing/AliasConfigurationFixture" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.seitenbau.com/testing/AliasConfigurationFixture AliasConfiguration.xsd ">

  <!-- ***** Login Echtsystem -->
  <alias name="username">           <value>usr</value></alias>
  <alias name="password">           <value>pwd</value></alias>

  <!-- ***** Login Simulator -->
  <!-- 
  <alias name="username">           <value>username</value></alias>
  <alias name="password">           <value>password</value></alias>
   -->
  <alias name="Login-Button">       <value>plogin</value></alias>
  <alias name="Logout-Link">        <value>linkLogout</value></alias>

  <!-- ***** uebersicht.do ***** -->
  <alias name="Weiterleitung-Link"> <value>link=Weiterleitung</value></alias>
 
</aliasConfiguration>
