=== RainerW/XMLFit/xmlfit-oaw/src/main/resources/net/sourceforge/xmlfit/model/component.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://xmlfit.sourceforge.net/schema/1.0/component" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:comp="http://xmlfit.sourceforge.net/schema/1.0/component">

    <complexType name="Fixture" abstract="true">
        <attribute name="type" type="string" use="optional"></attribute>
    </complexType>

    <complexType name="ActionFixture">
    	<complexContent>
    		<extension base="comp:Fixture">
    			<sequence>
    				<element name="command" type="comp:Command"
    					maxOccurs="unbounded" minOccurs="0">
    				</element>
    			</sequence>

    			<attribute name="type" type="string" default="fit.ActionFixture"></attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="ColumnFixture">
    	<complexContent>
    		<extension base="comp:Fixture">
    			<sequence>
    				<element name="column" type="comp:Column"
    					maxOccurs="unbounded" minOccurs="1">
    				</element>
    				<element name="row" type="comp:Row" maxOccurs="unbounded" minOccurs="0"></element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="Command">
    	<sequence>
    		<element name="target" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="value" type="string" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    	<attribute name="name" type="string" use="required"></attribute>
    </complexType>

    <complexType name="Column">
    	<attribute name="name" type="string" use="required"></attribute>
    </complexType>
    
    <complexType name="Row">
    	<sequence>
    		<element name="value" type="string" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>
    

    <complexType name="Component">
    	<sequence maxOccurs="unbounded" minOccurs="0">
            <group ref="comp:Fixture"></group>
    	</sequence>
    </complexType>

    <group name="Fixture">
      <choice>
        <element name="actionFixture" type="comp:ActionFixture"></element>
        <element name="columnFixture" type="comp:ColumnFixture"></element>
        <element name="comment" type="comp:CommentFixture"></element>
      </choice>
    </group>

    <complexType name="Components">
    	<sequence>
    		<element name="component" type="comp:Component" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <complexType name="CommentFixture">
        <sequence>
        <element name="heading" type="string" maxOccurs="1" minOccurs="0">
        </element>
        <element name="description" type="string" maxOccurs="1" minOccurs="0"></element>
      </sequence></complexType>

    <element name="component" type="comp:Component"></element>
</schema>

=== RainerW/XMLFit/xmlfit-oaw/src/test/resources/example-component.xml
<?xml version="1.0" encoding="UTF-8"?>
<component
	xmlns="http://xmlfit.sourceforge.net/component" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://xmlfit.sourceforge.net/component component.xsd ">

        <comment>
            <heading>User DB Setup</heading>
            <description>Setup the User DB for the Test.</description>
        </comment>
    
		<columnFixture type="UserDbFixture">
			<column name="id" />
			<column name="username" />
			<column name="password" />
			<row>
				<value>1</value>
				<value>${username}</value>
				<value>${password}</value>
			</row>
		</columnFixture>
		
        <comment>
            <heading>Login - for User ${username} and Password ${password}</heading>
            <description>The Fixture doese the Login with Username and Password.</description>
        </comment>
    
		<actionFixture>
			<command name="start">
				<value>LoginFixture</value>
			</command>
			<command name="enter">
				<target>username</target>
				<value>${username}</value>
			</command>
			<command name="enter">
				<target>password</target>
				<value>${password}</value>
			</command>
		</actionFixture>

</component>
